
name: Dogemone Wallet Release

on:
  workflow_dispatch:  # Allows manual triggering for nightly release

jobs:
  build-windows:
    name: Windows
    runs-on: windows-2019
    env:
      BOOST_ROOT: C:\thirdparties\boost-1.72.0
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Install Boost
        shell: cmd
        run: |
          choco install wget --no-progress
          wget -nv -O boost-installer.exe "https://sourceforge.net/projects/boost/files/boost-binaries/1.72.0/boost_1_72_0-msvc-14.2-64.exe/download"
          boost-installer.exe /dir=%BOOST_ROOT% /sp- /verysilent /suppressmsgboxes /norestart

      - name: Install OpenSSL
        run: choco install openssl

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          install-deps: 'true'

      - name: Build
        shell: powershell
        id: build
        env:
          GIT_REDIRECT_STDERR: '2>&1'
          VCINSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\'
        run: |
          $build_folder = "build"
          $release_name = "DogemoneWallet-win64-nightly"
          set CMAKE_PREFIX_PATH="$($qt5_cmake)"
          $qt5_cmake = "${{ env.Qt5_Dir }}/lib/cmake" -replace '[/]', '\'
          mkdir "$build_folder"
          cd "$build_folder"
          Start-Process cmake -ArgumentList "-DBOOST_ROOT=""$env:BOOST_ROOT"" -DBOOST_INCLUDE_DIRS=""$env:BOOST_ROOT/include"" -G ""Visual Studio 16 2019"" -A x64 -DARCH=default",".." -NoNewWindow -Wait
          Start-Process msbuild -ArgumentList "DogemoneWallet.sln","/p:Configuration=Release" -NoNewWindow -Wait
          mkdir Release
          cp DogemoneWallet.exe Release/

      - name: Upload Release
        uses: actions/upload-artifact@v3
        with:
          name: DogemoneWallet-nightly
          path: ./Release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./Release/DogemoneWallet.exe
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    name: macOS
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          install-deps: 'true'

      - name: Build
        id: build
        run: |
          mkdir -p build/release
          cd build/release
          cmake -DARCH=default -DCMAKE_BUILD_TYPE=Release ../..
          make
          mkdir Release
          cp DogemoneWallet.app Release/

      - name: Upload Release
        uses: actions/upload-artifact@v3
        with:
          name: DogemoneWallet-macos-nightly
          path: ./Release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./Release/DogemoneWallet.app
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y qtbase5-dev qttools5-dev qttools5-dev-tools libboost-all-dev

      - name: Build
        id: build
        run: |
          mkdir -p build/release
          cd build/release
          cmake -DARCH=default -DCMAKE_BUILD_TYPE=Release ../..
          make
          mkdir Release
          cp DogemoneWallet Release/

      - name: Upload Release
        uses: actions/upload-artifact@v3
        with:
          name: DogemoneWallet-linux-nightly
          path: ./Release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./Release/DogemoneWallet
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
